name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'      # triggers on push to any branch
  pull_request:
    branches:
      - '**'      # triggers on PRs from any branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Test backend
        working-directory: ./backend
        run: npm test || echo "No tests found"

      - name: Install frontend dependencies
        working-directory: ./Frontend
        run: npm install

      - name: Build frontend
        working-directory: ./Frontend
        run: npm run build

      # Deploy only when push is on main
      - name: Deploy frontend
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend/dist
